project:
  type: website

website:
  title: Amin Boumerdassi #"{{< fa house >}} | Amin Boumerdassi"
  search: false
  navbar:
    title: "{{< fa house >}} | Amin Boumerdassi"
    left:
      - href: index.qmd
        text: Bio
      - publications.qmd
      - href: talks_and_posters.qmd
        text: Talks & Posters
      - text: CV (TBA)
  page-footer:
    background: light
    left: "Copyright 2026, Amin Boumerdassi" 
    right: Made using [Quarto](https://quarto.org/) <img src="assets/quarto-icon.svg" alt="Quarto" width="16">, with minimal AI assistance.<br>Hosted on [GitHub Pages](https://github.com/AminBoumerdassi/AminBoumerdassi.github.io) {{< fa brands github >}}.


format:
  html:
    theme:
      # - cosmo
      # - brand
      light: brand
    css: styles.css
    toc: true

# Use https://heropatterns.com/ for background, specifically "topography"

filters:
  - auto-dark

execute:
  freeze: auto

