project:
  type: website

website:
  title: "Amin Boumerdassi"
  navbar:
    left:
      - href: index.qmd
        text: Bio
      - publications.qmd
  page-footer:
    background: light
    left: "Copyright 2026, Amin Boumerdassi" 
    right:
      - href: https://quarto.org/  
        text: "Made using Quarto"


format:
  html:
    theme:
      # - cosmo
      # - brand
      light: brand
    css: styles.css
    toc: true

filters:
  - auto-dark

execute:
  freeze: auto

