project:
  type: website

website:
  title: "{{< fa house >}} | Amin Boumerdassi"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Bio
      - publications.qmd
      - href: talks_and_posters.qmd
        text: Talks & Posters
      - text: CV (TBA)
  page-footer:
    background: light
    left: "Copyright 2026, Amin Boumerdassi" 
    right: "Made using [Quarto](https://quarto.org/), with minimal AI assistance."


format:
  html:
    theme:
      # - cosmo
      # - brand
      light: brand
    css: styles.css
    toc: true

filters:
  - auto-dark

execute:
  freeze: auto

