---
title: "Talks & Posters"
---

## 2025

---

<div class="grid-container">
  <div class="grid-item">**NZ Gravity Spring 2025 Workshop** <br>*Dunedin, NZ*<br>Talk: "Assessing glitch-induced bias and variability in EMRI parameter estimation"
  </div>
</div>
<br>

<div class="grid-container">
  <div class="grid-item">**NZ Gravity Autumn 2025 Workshop** <br>*Auckland, NZ*<br>Talk: "EMRIs and their role in GW science"
  </div>
</div>
<br>

## 2024

---

<div class="grid-container">
  <div class="grid-item">**New Zealand Statistical Association Conference**<br>*Wellington, NZ*<br>Talk: "Investigating the impact of gravitational wave glitches on the parameter estimation of extreme mass ratio inspirals"
  </div>
</div>
<br>

<div class="grid-container">
  <div class="grid-item">**New Zealand Mathematics and Statistics Postgraduate Conference**<br>*Christchurch, NZ*<br>Talk: "Investigating the impact of gravitational wave glitches on the parameter estimation of extreme mass ratio inspirals"
  </div>
</div>
<br>

<div class="grid-container">
  <div class="grid-item">**15th International LISA Symposium**<br>*Dublin, Ireland*<br>Poster: "Signal Detection of EMRIs with Convolutional Autoencoders"
  </div>
</div>
<br>

<div class="grid-container">
  <div class="grid-item">**NZ Gravity Summer 2024 Workshop** <br>*Auckland, NZ*<br>Talk: "Using Convolutional Autoencoders for Signal Detection of Extreme Mass Ratio Inspirals Detected by the LISA Mission"
  </div>
</div>
<br>

## 2023

---

<div class="grid-container">
  <div class="grid-item">**New Zealand Statistical Association Conference**<br>*Christchurch, NZ*<br>Talk: "Using Convolutional Autoencoders for Signal Detection of Extreme Mass Ratio Inspirals Detected by the LISA Mission"
  </div>
</div>
<br>

<div class="grid-container">
  <div class="grid-item">**New Zealand Mathematics and Statistics Postgraduate Conference**<br>*Wellington, NZ*<br>Talk: "Using Convolutional Autoencoders for Signal Detection of Extreme Mass Ratio Inspirals Detected by the LISA Mission"
  </div>
</div>
<br>

